// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DemoCounter: typeof import('./components/DemoCounter.vue')['default']
    HStack: typeof import('./layouts/HStack.vue')['default']
    IMyEmmysoft: typeof import('~icons/my/emmysoft')['default']
    IMyKtLogo: typeof import('~icons/my/kt-logo')['default']
    PaddingBox: typeof import('./layouts/PaddingBox.vue')['default']
    ResizableSplitLayout: typeof import('./layouts/ResizableSplitLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StackLayout: typeof import('./layouts/StackLayout.vue')['default']
    StackSpacer: typeof import('./layouts/StackSpacer.vue')['default']
    VStack: typeof import('./layouts/VStack.vue')['default']
  }
}
